### ISSUE TITLE
Improve/unify CSS Handling

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-rhei#13]
_have's:_
- distributed styling information e.g. regarding color themes
- code duplication per theme and among CSS files

_want's:_
- ability to define color schemes, e.g. 3 basic colors for general design + colors for emphasis (e.g. error, warning, info, success)
- ability to define/extract constants/variables
- support for includes / mixins
- no conflict with RAP specialities

_realisation:_
- using CSS pre processor: http://sass-lang.com/
  - Features: http://sass-lang.com/guide
  - Tutorials: http://thesassway.com/
  - color themes: http://www.guyroutledge.co.uk/blog/generating-multiple-colour-schemes-with-sass/ 
  - SASS compiler is triggered via ANT script that has been referenced as Eclipse project builder
  - instead of using theme contribution, extensions are provided via import declaration in main scss file
  - for SCSS / CSS editing support install Aptana studio: http://download.aptana.com/studio3/plugin/install

**Comment by fb71** [comment]
Das ist mal ein Ticket! Super Beschreibung! :)

**Comment by fb71** [comment]
**To do:**
- refactor all theming colors fonts into _standard.scss
- forms

**Comment by fb71** [comment]
Theme refactoring handled in new ticket #22.
