### ISSUE TITLE
Material Design: Generate icons from SVG

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rhei#15]
- generate different sizes (for different monitor resolution)
- set color (Material design icons are monochrom)

**Comment by fb71** [comment]
- works for the Dopplr.svg -- great! :)
- does not work fpr Material Design icons - all pixels seem to be black (PNG encoder or no alpha bit?)

**Comment by fb71** [comment]
Auto generated SVG icons seem to work! :)

FIXME: text/font in SVG (P4: zip.svg etc.) does not seem to geht renderer!?

**Comment by fb71** [comment]
Ok, Text ist geklärt. Dann schließe ich das Ticket. Oder habe ich was übersehen?

**Comment by joergreichert** [comment]
Nö, sollte soweit passen.
