### ISSUE TITLE
Support activating / deactivating form fields

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-rhei#28]
Currently Rhei Forms expects always a pure widget on the right side as with using an composite the layout gets broken, so it isn't possible to create a form field, that is preceded by a checkbox, to state if the value of the form field should be used (indicating a null value instead of just an empty value).

![inactivefields](https://cloud.githubusercontent.com/assets/994131/10275608/0d5cd1ec-6b49-11e5-8b6a-ae18a0c01514.png)

**Comment by fb71** [comment]
Have a look at org.polymap.rhei.field.BetweenFormField. It creates/uses a Composite as control.

What exactly is the problem with the broken layout?

And: if a field is not modified by the user then it is not dirty and not gets submitted (checkbox=off). **If** the user modifies something, then it is indicated in the UI (valid or not). (checkbox=on). In other word: the user indicates that the value of a field should be "used" by modifying it. What is the point of the additional checkbox?

**Comment by joergreichert** [comment]
Ok, using the same approach as BetweenFormField (= with composing FormFields) works. Thanks for the hint.
